# Generated by Django 4.1.2 on 2022-10-16 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
            ],
        ),
    ]
#The SQL statement created from the model is:

#CREATE TABLE "members_members" (
#"id" INT NOT NULL PRIMARY KEY AUTOINCREMENT,
#"firstname" varchar(255) NOT NULL,
#"lastname" varchar(255) NOT NULL);